[package]
name = "ao3fti-common"
version = "0.1.0"
edition = "2021"

workspace = ".."

[dependencies]
color-eyre = "0.6.1"
crossbeam-channel = "0.5"
http = "0.2"
serde = { version = "1.0", features = [ "derive" ] }
tracing = "0.1"
